#!/usr/bin/env python3

import collections
import hashlib
import json
import math
import shlex
import string

def hash_for_story(story):
    return hashlib.sha3_256(story.encode('utf8')).hexdigest()

def parse(file):
    lines = list(open(file).read().split('\n'))
    for line in lines:
        if line:
            yield json.loads(line)

def canon_word(word):
    return word.strip().strip(string.punctuation).lower()

def to_words(s):
    return set((canon_word(w) for w in s.split() if canon_word(w)))

def index(story_id, story):
    idx = collections.defaultdict(set)
    words = [canon_word(word) for word in story.split() if not all((c == '-' for c in word))]
    words = set((word for word in words if word))
    for word in words:
        idx[word].add(story_id)
    return idx

def entropies(strings):
    counts = collections.defaultdict(int)
    total = 0
    for s in strings:
        for c in s:
            counts[c] += 1
            total += 1
    return dict(((c, (count/total)) for (c, count) in counts.items()))

def shannon_entropy(p, s):
    total = 0
    for c in s:
        total += 0 - p.get(c, 0.0) * math.log2(p.get(c, 0.000000001))
    return total

class Session:

    def __init__(self, story_files):
        self._stories = {}
        idx = collections.defaultdict(list)
        for story_file in story_files:
            for story in parse(story_file):
                story_id = hash_for_story(story)
                self._stories[story_id] = story
                for word, ids in index(story_id, story).items():
                    idx[word] += ids
        self._index = dict(idx)
        self._entropies = entropies(self._stories.values())

    def search(self, *words):
        stories = set(self._stories.keys())
        for word in to_words(' '.join(words)):
            if not word:
                continue
            stories &= set(self._index.get(canon_word(word), set()))
        return [self._stories[story_id] for story_id in stories]

    def suggest(self, *words, count=10):
        stories = self.search(*words)
        ranked_words = {}
        for story in stories:
            for word in to_words(story):
                ranked_words[word] = math.log2(len(self._index.get(word, []))) *  shannon_entropy(self._entropies, word)
        by_rank = sorted(((rank, word) for (word, rank) in ranked_words.items()), reverse=True)
        return [word for (rank, word) in by_rank[:count]]

def main(args):
    session = Session(args)
    try:
        while True:
            cmdline = shlex.split(input('gatherbrained# '))
            if not cmdline:
                continue
            cmd, args = cmdline[0], cmdline[1:]
            if cmd == 'search':
                if not args:
                    args = prev_search
                elif args[0] == '+':
                    args = prev_search + args[1:]
                prev_search = args
                for story in sorted(session.search(*args)):
                    print(story + '\n')
            elif cmd == 'suggest':
                if not args:
                    args = prev_search
                elif args[0] == '+':
                    args = prev_search + args[1:]
                prev_search = args
                for word in session.suggest(*args):
                    print(word)
            else:
                print("unknown command")
    except EOFError as e:
        pass
    except KeyboardInterrupt as e:
        pass
    except Exception as e:
        raise

if __name__ == '__main__':
    import sys
    main(sys.argv[1:])
